import { useState } from "react";
import type { PipelineResponse } from "../contracts";
import { Badge, Card, ScoreBar } from "./ui";

type Tab = "overview" | "candidates" | "analysis" | "pairing" | "pipeline";
const labels: Record<Tab, string> = { overview: "Overview", candidates: "Candidates", analysis: "Analysis", pairing: "Pairing", pipeline: "Pipeline" };
const criterionLabels: Record<string, string> = { domain_expertise: "Domain Expertise", transformation_leadership: "Transformation Leadership", operational_execution: "Operational Execution", stakeholder_management: "Stakeholder Management", crisis_management: "Crisis Management", innovation_digital: "Innovation & Digital", strategic_scalability: "Strategic Scalability" };

function CriterionScoringPanel({ scores }: { scores: PipelineResponse["candidate_evaluations"][number]["criteria_scores"] }) {
  const [open, setOpen] = useState(false);
  return <div className="mt-3 border-t border-white/10 pt-3"><button onClick={() => setOpen(!open)} className="text-xs text-white/40">Criterion Scoring {open ? "▲" : "▼"}</button>{open && <div className="mt-3 space-y-2">{Object.entries(scores).map(([key, score]) => <div key={key} className="rounded-lg border border-white/10 bg-black/20 px-4 py-3"><div className="flex justify-between text-xs"><span className="font-semibold">{criterionLabels[key] ?? key}</span><span>Model conf: {Math.round(score.confidence * 100)}% · <b className="text-amber-400">{score.score}/10</b></span></div><p className="mt-1 text-[11px] text-white/40">{score.evidence}</p></div>)}</div>}</div>;
}

export function DecisionResults({ response }: { response: PipelineResponse }) {
  const [tab, setTab] = useState<Tab>("overview");
  const hasPairing = Boolean(response.pairing_result);
  const tabs = (Object.keys(labels) as Tab[]).filter((item) => item !== "pairing" || hasPairing);
  return <div className="mx-auto max-w-3xl space-y-6 px-6 py-10"><div className="flex flex-wrap gap-2">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-3 py-1.5 text-xs ${tab === item ? "bg-amber-400 text-black" : "bg-white/10 text-white/60"}`}>{item}</button>)}</div>
    {tab === "overview" && <div className="space-y-4"><Card><h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-white/40">Recommendation</h3><div className="text-xl font-bold">{response.decision_result.recommended_candidate_name}</div><p className="mt-2 text-sm text-white/60">{response.decision_result.key_reason}</p></Card><Card><h3 className="mb-4 text-xs font-semibold uppercase tracking-widest text-white/40">Executive Summary</h3><div className="grid grid-cols-2 gap-3 text-xs">{Object.entries(response.executive_summary).map(([key, value]) => <div key={key}><div className="capitalize text-white/40">{key.replace("_", " ")}</div><div className="text-white/80">{value}</div></div>)}</div></Card>{response.trade_offs.length > 0 && <Card><h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-white/40">Trade-offs</h3>{response.trade_offs.map((tradeOff, index) => <div key={index} className="mb-3 border-l-2 border-amber-400/30 pl-3"><div className="text-sm">{tradeOff.title}</div><div className="text-xs text-white/50">{tradeOff.description}</div></div>)}</Card>}</div>}
    {tab === "candidates" && <div className="space-y-3">{response.candidate_evaluations.map((candidate, index) => <Card key={candidate.candidate_id} className={index === 0 ? "border-amber-400/20" : ""}><div className="mb-3 flex items-start justify-between"><div><div className="flex gap-2"><span className="text-white/30">#{candidate.rank}</span><b>{candidate.candidate_name}</b>{index === 0 && <Badge color="amber">Winner</Badge>}</div><div className="mt-1 flex gap-1">{candidate.strategic_labels.map((label) => <Badge key={label}>{label}</Badge>)}</div></div><div className="text-right"><b>{candidate.weighted_fit_score.toFixed(1)}</b><div className="text-xs text-white/40">WFS</div></div></div><div className="grid grid-cols-3 text-center text-xs"><div><b>{candidate.risk_adjusted_score.toFixed(1)}</b><div className="text-white/40">Risk Adj.</div></div><div><b>{candidate.expected_outcome_score.toFixed(1)}</b><div className="text-white/40">Outcome</div></div><div><b>{Math.round(candidate.overall_confidence * 100)}%</b><div className="text-white/40">Model Conf.</div></div></div>{candidate.winner_reason && <p className="mt-3 border-t border-white/10 pt-3 text-xs italic text-amber-300">{candidate.winner_reason}</p>}<CriterionScoringPanel scores={candidate.criteria_scores}/></Card>)}</div>}
    {tab === "analysis" && <div className="space-y-4"><Card><h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-white/40">Scenario Analysis</h3><p className="text-sm text-white/70">{response.scenario_analysis.weight_rationale}</p><div className="mt-3 flex flex-wrap gap-1">{response.scenario_analysis.key_pressures.map((pressure) => <Badge key={pressure} color="blue">{pressure}</Badge>)}</div></Card><Card><h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-white/40">Adaptability Profiles</h3>{response.adaptability_profiles.map((profile) => <div key={profile.candidate_name} className="mb-4"><div className="flex justify-between text-xs"><span>{profile.candidate_name}</span><span>{profile.adaptability_score}/100</span></div><ScoreBar value={profile.adaptability_score} max={1} color="#34d399"/><p className="mt-1 text-xs italic text-white/40">{profile.resilience_note}</p>{profile.cross_scenario_consistency === "not_measured" && <p className="text-[11px] italic text-white/30">Cross-scenario consistency: not measured (requires running multiple scenarios).</p>}</div>)}</Card>{response.confidence_evidence_reviews.some((review) => review.confidence_evidence_flags.length > 0) && <Card><h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-white/40">Confidence & Evidence Flags</h3>{response.confidence_evidence_reviews.filter((review) => review.confidence_evidence_flags.length > 0).map((review) => <div key={review.candidate_id}><b className="text-sm">{review.candidate_name}</b>{review.confidence_evidence_flags.map((flag, index) => <div key={index} className="mt-1 border-l-2 border-amber-400/40 pl-2 text-xs"><span className="text-amber-300">{flag.type}</span><span className="ml-2 text-white/40">{flag.description}</span></div>)}</div>)}</Card>}</div>}
    {tab === "pairing" && response.pairing_result?.status === "unavailable" && <Card><h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-white/40">Pairing Unavailable</h3><p className="text-sm text-white/70">We couldn't evaluate leadership pairs for this run. No pair result is available — nothing below is a real recommendation.</p></Card>}
    {tab === "pairing" && response.pairing_result?.status === "ok" && <Card className="border-amber-400/20"><h3 className="mb-4 text-xs font-semibold uppercase tracking-widest text-white/40">Best Leadership Pair</h3><div className="mb-4 flex gap-3"><b>{response.pairing_result.best_pair.pair[0]}</b><span className="text-amber-400">+</span><b>{response.pairing_result.best_pair.pair[1]}</b><Badge color="amber">{response.pairing_result.best_pair.pair_score.toFixed(1)} / 10</Badge></div><p className="text-xs text-white/60">{response.pairing_result.best_pair.explanation}</p></Card>}
    {tab === "pipeline" && <div className="space-y-3">{response.pipeline_stage_outputs.map((stage) => <Card key={stage.stage_name}><div className="flex justify-between"><b className="text-sm">{stage.stage_name}</b><Badge>{stage.stage_role.includes("LLM") ? "LLM" : "Deterministic"}</Badge></div><p className="mt-2 text-xs text-white/50">{stage.stage_role}</p><p className="mt-3 border-t border-white/10 pt-3 text-xs italic text-white/40">{stage.summary}</p></Card>)}</div>}
    <div className="space-y-1 pt-2 text-center text-[11px] text-white/25">{response.run_metadata && <><div>Evaluated with {response.run_metadata.provider} ({response.run_metadata.model}) · {response.run_metadata.logicalProviderStageCount} stage{response.run_metadata.logicalProviderStageCount === 1 ? "" : "s"} · {response.run_metadata.providerAttemptCount} OpenAI call{response.run_metadata.providerAttemptCount === 1 ? "" : "s"} · {response.run_metadata.totalTokens.toLocaleString()} tokens</div><div>{response.run_metadata.estimatedCostUsd !== null ? `Estimated cost: ~$${response.run_metadata.estimatedCostUsd.toFixed(4)} (approximate, not an invoice)` : "Estimated cost: unavailable for this model"}</div></>}</div>
  </div>;
}
