import { DECISION_MODES } from "../constants";
import type { CandidateInput, EvaluationRequest } from "../contracts";
import { Card } from "./ui";

type Props = {
  role: { title: string; description: string }; setRole: (value: { title: string; description: string }) => void;
  scenarios: string[]; setScenarios: (value: string[]) => void; scenario: string; setScenario: (value: string) => void;
  decisionMode: EvaluationRequest["decision_mode"]; setDecisionMode: (value: EvaluationRequest["decision_mode"]) => void;
  candidates: CandidateInput[]; setCandidates: (value: CandidateInput[]) => void; enablePairing: boolean; setEnablePairing: (value: boolean) => void;
  onRun: () => void; isRunning: boolean; onGenerateScenarios: () => void; isGeneratingScenarios: boolean;
  onLoadDefaults: () => void; onResetInputs: () => void; aiEnabled: boolean;
};
const input = "w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white placeholder-white/30 focus:outline-none";
const cn = (...classes: (string | false)[]) => classes.filter(Boolean).join(" ");

export function EvaluationForm(props: Props) {
  const { role, setRole, scenarios, setScenarios, scenario, setScenario, decisionMode, setDecisionMode, candidates, setCandidates, enablePairing, setEnablePairing, onRun, isRunning, onGenerateScenarios, isGeneratingScenarios, onLoadDefaults, onResetInputs, aiEnabled } = props;
  const canRun = Boolean(role.title.trim() && role.description.trim() && scenario && candidates.filter((candidate) => candidate.name.trim() && candidate.description.trim()).length >= 2);
  return <div className="mx-auto max-w-3xl space-y-6 px-6 py-10"><h2 className="text-xl font-bold">Configure Evaluation</h2>
    {!aiEnabled && <Card className="border-amber-400/20 bg-amber-400/5"><p className="text-sm font-semibold text-amber-200">AI generation is unavailable in this environment.</p><p className="mt-1 text-xs text-white/60">You can still use Default Entries or add scenarios and candidates manually.</p></Card>}
    <Card><div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><label className="text-xs font-semibold uppercase tracking-widest text-white/50">Role</label><div className="flex gap-2"><button onClick={onGenerateScenarios} disabled={isGeneratingScenarios || !role.title.trim() || !role.description.trim() || !aiEnabled} className="rounded-lg bg-blue-400/15 px-3 py-1.5 text-xs font-semibold text-blue-300 disabled:opacity-40">{isGeneratingScenarios ? "Generating..." : "Generate Scenarios"}</button><button onClick={onLoadDefaults} className="rounded-lg bg-amber-400 px-3 py-1.5 text-xs font-semibold text-black">Default Entries</button><button onClick={onResetInputs} className="rounded-lg bg-white/10 px-3 py-1.5 text-xs font-semibold">Reset</button></div></div><input className={input} placeholder="Role title (e.g. VP of Product)" value={role.title} onChange={(event) => setRole({ ...role, title: event.target.value })}/><textarea className={`${input} resize-none`} rows={3} placeholder="Role description — context, responsibilities, must-haves..." value={role.description} onChange={(event) => setRole({ ...role, description: event.target.value })}/></div></Card>
    <Card><div className="flex items-center justify-between"><label className="text-xs font-semibold uppercase tracking-widest text-white/50">Scenarios ({scenarios.length})</label><button onClick={() => setScenarios([...scenarios, ""])} className="text-xs text-amber-400">+ Add Scenario</button></div><div className="mt-3 space-y-2">{scenarios.map((item, index) => <div key={`${index}-${item}`} className="flex gap-2"><input className={input} value={item} placeholder={`Scenario ${index + 1}`} onChange={(event) => { const next = [...scenarios]; next[index] = event.target.value; setScenarios(next); if (scenario === item) setScenario(event.target.value); }}/><button onClick={() => { const next = scenarios.filter((_, itemIndex) => itemIndex !== index); setScenarios(next); if (scenario === item) setScenario(next[0] || ""); }} className="px-2 text-xs text-white/30">✕</button></div>)}</div></Card>
    <div className="grid grid-cols-2 gap-4"><Card><label className="mb-2 block text-xs font-semibold uppercase tracking-widest text-white/50">Active Scenario</label><select className={input} value={scenario} onChange={(event) => setScenario(event.target.value)}>{scenarios.map((item, index) => <option key={`${index}-${item}`} value={item}>{item || `Scenario ${index + 1}`}</option>)}</select></Card><Card><label className="mb-2 block text-xs font-semibold uppercase tracking-widest text-white/50">Decision Mode</label><select className={input} value={decisionMode} onChange={(event) => setDecisionMode(event.target.value as EvaluationRequest["decision_mode"])}>{DECISION_MODES.map((mode) => <option key={mode.value} value={mode.value}>{mode.label}</option>)}</select></Card></div>
    <Card><div className="flex items-center justify-between"><label className="text-xs font-semibold uppercase tracking-widest text-white/50">Candidates ({candidates.length})</label><button onClick={() => setCandidates([...candidates, { id: `c${Date.now()}`, name: "", description: "" }])} className="text-xs text-amber-400">+ Add</button></div><div className="mt-3 space-y-3">{candidates.map((candidate, index) => <div key={candidate.id} className="space-y-1.5 rounded-lg border border-white/5 p-3"><div className="flex gap-2"><input className={input} placeholder="Candidate name" value={candidate.name} onChange={(event) => { const next = [...candidates]; next[index] = { ...candidate, name: event.target.value }; setCandidates(next); }}/><button onClick={() => setCandidates(candidates.filter((_, candidateIndex) => candidateIndex !== index))} className="text-xs text-white/30">✕</button></div><textarea className={`${input} resize-none text-xs`} rows={2} placeholder="Background, experience, strengths, context..." value={candidate.description} onChange={(event) => { const next = [...candidates]; next[index] = { ...candidate, description: event.target.value }; setCandidates(next); }}/></div>)}</div></Card>
    <Card><div className="flex gap-4"><button onClick={() => setEnablePairing(!enablePairing)} className={cn("relative mt-0.5 h-6 w-11 rounded-full", enablePairing ? "bg-amber-400" : "bg-white/20")}><span className={cn("absolute top-1 h-4 w-4 rounded-full bg-white", enablePairing ? "left-6" : "left-1")}/></button><div><div className="text-sm font-semibold">Simulate leadership pairing</div><p className="text-xs text-white/50">Find the best pair for this scenario by testing complementarity, cohesion, and conflict risk.</p></div></div></Card>
    <button onClick={onRun} disabled={isRunning || !canRun || !aiEnabled} className="w-full rounded-xl bg-amber-400 py-3 text-sm font-bold text-black disabled:opacity-50">{isRunning ? "Running Pipeline..." : "▶ Run Decision Pipeline"}</button>{!canRun && <p className="text-xs text-white/40">Add a role, at least one scenario, and at least two complete candidate profiles.</p>}
  </div>;
}
